# Generated by Django 3.2.9 on 2021-11-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='descricao',
            field=models.TextField(),
        ),
    ]
