# Generated by Django 3.2.9 on 2021-11-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_postagem_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='titulo',
            field=models.CharField(default='Sem Titulo', max_length=30),
        ),
    ]
